### ISSUE TITLE
Same keys produces invalid JSON (& later one overwrites the former one)

### ISSUE THREAD

**Issue by zrzka** [angelcam/rust-slog-loggly#1]
Let's assume `l` is an existing logger. Try the following example:

```rust
let l2 = l.new(o!("misc" => "abc"));
info!(l2, "Hallo"; "misc" => "dce");
```

`TerminalLogger` drain logs:

```
INFO Hallo, misc: dce, misc: abc
```

This drain sends following raw message:

```json
{"level":"info","file":"src/main.rs:73","message":"Hallo","misc":"abc","misc":"dce"}
```

And the final `json` (in Loggly) contains jsut `"misc": "dce"` and the `"misc": "abc"` is completely ignored.

Not sure what to do with this, but we have to handle it somehow. What about simple `','.join(miscs)`?

**Comment by zrzka** [comment]
Or we should just left this as it is, inform about it in docs and forget it? This can be fixed by some kind of super drain which handles these duplicate keys.

**Comment by operutka** [comment]
IMHO keys passed via macro should override logger keys, i.e. the solution would be constructing temporary HashMap before message serialization.

**Comment by zrzka** [comment]
Also consider this example:

```rust
let l2 = l.new(o!("misc" => "abc"));
let l3 = l2.new(o!("misc" => "def"));

info!(l3, "Haha");
```

This ends up as `"misc": "abc"` in Loggly and `"misc": "def"` is ignored.
