### ISSUE TITLE
Enhance README.md

### ISSUE THREAD

**Issue by zrzka** [angelcam/rust-slog-loggly#2]
Because we did open source this crate, we should polish README.md. Take inspiration from slog for example:

* https://github.com/slog-rs/slog
* https://crates.io/crates/slog

Add build status, remove Documentation section, provide links to docs.rs, crates.io, add more info, ...

**Comment by operutka** [comment]
Docs, crates.io and Travis links have been added. I'd like to keep the README simple, so more info will be added once it's needed.
