### ISSUE TITLE
Field originally sent as an object and later as a concrete value or an array. Removed all json fields.

### ISSUE THREAD

**Issue by zrzka** [angelcam/rust-slog-loggly#4]
Was searching for one specific message in Loggly and wasn't able to find it. Then I found it ...

<img width="677" alt="screen shot 2018-05-04 at 08 52 15" src="https://user-images.githubusercontent.com/1084172/39615821-7b5ac8be-4f78-11e8-8204-04d6eabecb29.png">

... but with notification ...

`Field originally sent as an object and later as a concrete value or an array. Removed all json fields.`

Raw message at the end of this issue (or `tag:rust-recorder-test-localhost` & `2018-05-04 08:25:17.546`). Here's the [log message creation](https://github.com/angelcam/rust-recorder/blob/feature-logging/src/recording/publisher.rs#L78-L86) (sorry for the link to the private repo, but you've got access).

I guess that's because `sqs_message` contains serialized SQS JSON message (`String`)? Probably bug in the Loggly, but the question is if we can do something with it?

```json
{
    "level": "error",
    "file": "src/recording/publisher.rs:78",
    "message": "Failed to publish archive",
    "camera_id": "83",
    "recording_id": "f2c3dfd8-78a0-4f0d-b2fe-e5154abd00f0",
    "recorder_id": "8823fc3c-628f-411f-b972-4958fa283b15",
    "instance_id": "localhost",
    "error": "Failed to put object: S3 PUT failed: TimeOut",
    "misc": "camera_setup: common, rotation: 60, retention: 1 hours, format: hls, sqs_message: {\"id\":\"2c70db53-2d52-44e0-bb45-69f5fcad1f07\",\"recordingId\":\"f2c3dfd8-78a0-4f0d-b2fe-e5154abd00f0\",\"format\":\"hls\",\"filename\":\"2c70db53-2d52-44e0-bb45-69f5fcad1f07.tar\",\"size\":17304064,\"region\":\"eu-central-1\",\"startsAt\":\"2018-05-04T06:23:34+00:00\",\"endsAt\":\"2018-05-04T06:24:34+00:00\",\"expiresAt\":\"2018-05-04T07:24:34+00:00\",\"items\":[{\"name\":\"segment-360352.ts\",\"startsAt\":\"2018-05-04T06:23:34+00:00\",\"endsAt\":\"2018-05-04T06:23:40+00:00\",\"duration\":6.0,\"keyframe\":true},{\"name\":\"segment-360353.ts\",\"startsAt\":\"2018-05-04T06:23:40+00:00\",\"endsAt\":\"2018-05-04T06:23:46+00:00\",\"duration\":6.0,\"keyframe\":true},{\"name\":\"segment-360354.ts\",\"startsAt\":\"2018-05-04T06:23:46+00:00\",\"endsAt\":\"2018-05-04T06:23:52+00:00\",\"duration\":6.0,\"keyframe\":true},{\"name\":\"segment-360355.ts\",\"startsAt\":\"2018-05-04T06:23:52+00:00\",\"endsAt\":\"2018-05-04T06:23:58+00:00\",\"duration\":6.0,\"keyframe\":true},{\"name\":\"segment-360356.ts\",\"startsAt\":\"2018-05-04T06:23:58+00:00\",\"endsAt\":\"2018-05-04T06:24:04+00:00\",\"duration\":6.0,\"keyframe\":true},{\"name\":\"segment-360357.ts\",\"startsAt\":\"2018-05-04T06:24:04+00:00\",\"endsAt\":\"2018-05-04T06:24:10+00:00\",\"duration\":6.0,\"keyframe\":true},{\"name\":\"segment-360358.ts\",\"startsAt\":\"2018-05-04T06:24:10+00:00\",\"endsAt\":\"2018-05-04T06:24:16+00:00\",\"duration\":6.0,\"keyframe\":true},{\"name\":\"segment-360359.ts\",\"startsAt\":\"2018-05-04T06:24:16+00:00\",\"endsAt\":\"2018-05-04T06:24:22+00:00\",\"duration\":6.0,\"keyframe\":true},{\"name\":\"segment-360360.ts\",\"startsAt\":\"2018-05-04T06:24:22+00:00\",\"endsAt\":\"2018-05-04T06:24:28+00:00\",\"duration\":6.0,\"keyframe\":true},{\"name\":\"segment-360361.ts\",\"startsAt\":\"2018-05-04T06:24:28+00:00\",\"endsAt\":\"2018-05-04T06:24:34+00:00\",\"duration\":6.0,\"keyframe\":true}]}, sqs_queue: https://obfuscated, s3_expires_at: 2018-05-04T07:24:34+00:00, s3_storage_class: REDUCED_REDUNDANCY, s3_bucket: obfuscated, s3_key: 2c70db53-2d52-44e0-bb45-69f5fcad1f07.tar"
}
```

**Comment by zrzka** [comment]
Hmm, it seems that Loggly has some issues. Check `tag:rec-publisher-prod`. These mapping conflicts are here since `2018-05-04 05:09:06.714`. Previous log message are okay.

**Comment by operutka** [comment]
As discussed - it isn't a bug, it's Loggly feature. The mapping conflicts are caused by other applications using the same fields.

**Comment by izackv** [comment]
@operutka Can you point to the discussion regarding this "Feature"?
I'm trying to understand what and where should be change to stop loggly from giving this type of error...

**Comment by zrzka** [comment]
@izackv here's what's going on ...

Let's say you already sent a log message containing:

```json
{
  "code": 123
}
```

You changed your mind and would like to send it as string:

```json
{
  "code": "123"
}
```

And it fails. Field in all messages must have same type (number, string, ...). You can't do this. And it applies to all log messages in your account (you can't differentiate this by `tag` for example).

Actually you can do this, but you have to wait till all messages expire in Loggly.

I was puzzled as well, but the error message `Field originally sent as an object and later as a concrete value or an array. Removed all json fields.` says it. You did send field `X` as type `Y` and now you're trying to send field `X` as type `Z` where `type(Y) != type(Z)`.

And this is the Loggly feature @operutka was referring to.

**Comment by izackv** [comment]
@zrzka Many thanks for the explanation!

**Comment by ezmiller** [comment]
@zrzka is this feature documented somewhere? Does it also apply to cases where a value that is provided is null in some cases?

**Comment by operutka** [comment]
@ezmiller I suggest asking directly someone from Loggly. We can only guess here.

**Comment by zrzka** [comment]
@ezmiller honestly, I don't remember if it's documented or not (more than year ago).

Re null question - maybe @operutka knows? IIRC null should be fine, but I'd rather wait for Ondrej.

**Comment by stephent** [comment]
It would be super helpful if the error message stated which field had caused this, e.g. 

`Field 'badfield' originally sent as an object and later as a concrete value or an array. Removed all json fields.`

**Comment by operutka** [comment]
@stephent That'd be great! Unfortunately, there's nothing we can do about it here. This is an unofficial Loggly client. You'd have to ask directly people from Loggly.
