### ISSUE TITLE
Upload interval

### ISSUE THREAD

**Issue by zrzka** [angelcam/rust-slog-loggly#5]
I can specify `batch_size`, but it's unclear to me (without looking to source code) if messages are uploaded in some interval even if I don't reach `batch_size`. Let's say I've got 8 message, but `batch_size` is 10. What happens?

Shouldn't we add `upload_interval` to `LogglyDrainBuilder`, so, user of this library will be able to control this as well? It should upload all messages in the queue in specified `upload_interval` even if `batch_size` limit isn't reached.

This can be pretty useful in our recorder for example. When we receive SIGTERM, we're waiting for 10 seconds before we actually finish it. But it's fuzzy & wild guess that the Loggly drain will finish it's job. If `upload_interval` will be supported, I can say that we should wait `upload_interval() + 2s` for example and then quit it.

Or any other alternative allowing me to reach the same goal. Unfuzzy this process and remove wild guesses.

This should be also documented as well, I mean, how the `LogglyDrain` behaves from this point of view.

**Comment by operutka** [comment]
The batch size is not fixed. It's maximum batch size. In other words, if there is not enough messages in the queue to fill the batch, they are sent anyway. There's no need for upload interval. I'll improve the documentation.

**Comment by operutka** [comment]
The doc string has been clarified.
